// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tischtennis_Shop.Data;

namespace Tischtennis_Shop.Migrations
{
    [DbContext(typeof(TischtennisShopContext))]
    [Migration("20210505155749_InitialCreate7")]
    partial class InitialCreate7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tischtennis_Shop.Models.Belag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Belag_Art")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildpfad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Menge_Rot")
                        .HasColumnType("int");

                    b.Property<int>("Menge_Schwarz")
                        .HasColumnType("int");

                    b.Property<int?>("MitarbeiterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("MitarbeiterID");

                    b.ToTable("Belag");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Kunde", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hausnummer")
                        .HasColumnType("int");

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Postleitzahl")
                        .HasColumnType("int");

                    b.Property<string>("Straße")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Kunde");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Rechnung", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Gesamtbetrag")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("KundeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KundeID");

                    b.ToTable("Rechnung");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Verkaufte_Ware", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BelagID")
                        .HasColumnType("int");

                    b.Property<string>("Farbe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gesamtpreis")
                        .HasColumnType("int");

                    b.Property<int>("Menge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis_je_Stueck")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RechnungID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("BelagID");

                    b.HasIndex("RechnungID");

                    b.ToTable("Verkaufte_Ware");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Belag", b =>
                {
                    b.HasOne("Tischtennis_Shop.Models.Mitarbeiter", "Mitarbeiter")
                        .WithMany("zulaetzgeaendeterbelag")
                        .HasForeignKey("MitarbeiterID");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Rechnung", b =>
                {
                    b.HasOne("Tischtennis_Shop.Models.Kunde", "Kunde")
                        .WithMany("Kunden_Rechnungen")
                        .HasForeignKey("KundeID");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Verkaufte_Ware", b =>
                {
                    b.HasOne("Tischtennis_Shop.Models.Belag", "Belag")
                        .WithMany()
                        .HasForeignKey("BelagID");

                    b.HasOne("Tischtennis_Shop.Models.Rechnung", "Rechnung")
                        .WithMany("Gekaufte_Waren")
                        .HasForeignKey("RechnungID");
                });
#pragma warning restore 612, 618
        }
    }
}
