// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tischtennis_Shop.Data;

namespace Tischtennis_Shop.Migrations
{
    [DbContext(typeof(TischtennisShopContext))]
    [Migration("20210427162405_InitialCreate4")]
    partial class InitialCreate4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tischtennis_Shop.Models.Belag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Belag_Art")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bildpfad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Menge_Rot")
                        .HasColumnType("int");

                    b.Property<int>("Menge_Schwarz")
                        .HasColumnType("int");

                    b.Property<int?>("MitarbeiterID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preis")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("MitarbeiterID");

                    b.ToTable("Belag");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Mitarbeiter", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mitarbeiter");
                });

            modelBuilder.Entity("Tischtennis_Shop.Models.Belag", b =>
                {
                    b.HasOne("Tischtennis_Shop.Models.Mitarbeiter", null)
                        .WithMany("zulaetzgeaendeterbelag")
                        .HasForeignKey("MitarbeiterID");
                });
#pragma warning restore 612, 618
        }
    }
}
